apiVersion: v1
kind: Service
metadata:
  name: auth-ui-lb
  namespace: default
spec:
  selector:
    app: auth-ui
  type: LoadBalancer
  ports:
    - name: "http-port"
      port: 9999
      targetPort: 9999