apiVersion: v1
kind: Secret
metadata:
  name: auth-ui-config-secret
  namespace: default
type: Opaque
stringData:
  config.yml: |
    port: "9999"

    # Need to change for every cluster
    ## deployed cluster name
    clusterName: "commanda-ahuenaya.dev"
    ## deployed apiAddress
    ## template variables https://<ip-address-master-node>:6433 OR ur LB address with dicrover master node
    ## or other address witch poin in worked alredy exist kubeconfig
    cluesterApiAddress: "https://cluster.ru:6443"


    # Dont need to change
    ## default path to CA cluster cert if it placed in pods with serviceaccount 
    clusterCAPath: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    ## keycloak vars
    keycloakHost: "https://keycloak.com"
    keycloakRealm: "master"

    idpIssuerUrl: "https://keycloak.com/realms/master"
    clientID: "kubernetes"
    clientSecret: ""

    usernameClaim: "preferred_username"

    # App vars
    TemplatesDir: "templates"
    jwtsecret: "SECRET"
    cookieSecure: false
